### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by nicholasluimy** [lowjiajin/snowfall#1]
Where's the code 
![image](https://user-images.githubusercontent.com/8996422/86335833-de605380-bc03-11ea-9cf1-a053c0159a2e.png)

**Comment by lowjiajin** [comment]
You wanna volunteer to write it? :p

**Comment by nicholasluimy** [comment]
#opensource

I nominate @gnosis-agora

**Comment by lowjiajin** [comment]
Works now
